In [1]:
from libpyhat.emi.emi import emi
import pandas as pd
import numpy as np

In [2]:
# Read the .csv file into a dataframe.  Ignore "meta" columns and labels.
file = "salinasA_corrected_gt_flat.csv"
df = pd.read_csv(file, header=[0,1])

In [3]:
emi(df, "FIPPI", q=6)
emi(df, "PPI", q=6)
emi(df, "ATGP", q=6)
emi(df, "NFINDR", q=6)

In [4]:
df

     meta                   wvl                                      ...       \
      row col ground_truth  360 369.7 379.4 389.1 398.8 408.5 418.2  ... 2450
0       1   1            1  376   481   665  1086  1378  1399  1359  ...   11
1       2   1            1  376   481   665  1086  1378  1399  1359  ...   11
2       3   1            1  363   493   684  1134  1409  1420  1339  ...   10
3       4   1            1  369   477   669  1091  1350  1444  1356  ...    8
4       5   1            1  369   477   669  1091  1350  1444  1356  ...    8
...   ...  ..          ...  ...   ...   ...   ...   ...   ...   ...  ...  ...
7133   79  86            0  445   574   727  1212  1618  1692  1685  ...  117
7134   80  86            0  447   559   795  1298  1640  1735  1663  ...  119
7135   81  86            0  447   559   795  1298  1640  1735  1663  ...  119
7136   82  86            0  365   474   728  1256  1608  1670  1623  ...  115
7137   83  86            0  365   474   728  1256  1608  1670  1623  ...  115

                              endmembers
     2460 2470 2480 2490 2500      FIPPI PPI ATGP NFINDR
0      10    9    4    1    2          0   0    0      0
1      10    9    4    1    2          0   0    0      0
2      10    9    6    0   -1          0   0    0      0
3      12    7    4    3    3          0   0    0      0
4      12    7    4    3    3          0   0    0      0
...   ...  ...  ...  ...  ...        ...  ..  ...    ...
7133  175  122   62   21   39          0   0    0      0
7134  171  118   66   24   39          0   0    0      0
7135  171  118   66   24   39          0   0    0      0
7136  165  120   63   19   41          0   0    0      0
7137  165  120   63   19   41          0   1    0      0

[7138 rows x 211 columns]

In [6]:
df[df['endmembers'].sum(axis=1)>0]

     meta                   wvl                                      ...       \
      row col ground_truth  360 369.7 379.4 389.1 398.8 408.5 418.2  ... 2450
25     26   1            0  384   487   660  1136  1379  1444  1396  ...   51
83      1   2            1  447   481   731  1086  1378  1444  1340  ...    5
509    12   7            1  452   568   744  1131  1412  1445  1339  ...   10
1082    4  14            1  369   477   669  1091  1380  1444  1337  ...    0
1091   13  14            1  387   483   741  1089  1383  1442  1359  ...  172
1174   13  15            1  330   362   382   375   396   417   415  ...   12
2372   49  29            0  373   474   731  1089  1378  1441  1374  ...   80
2373   50  29           13  290   489   741  1090  1409  1420  1375  ...   80
2374   51  29           13  376   391   605  1095  1382  1446  1395  ...   72
4859   46  59           14  369   408   607   961  1233  1283  1263  ...   37
5310   82  64            0  365   558   859  1427  1844  1987  1989  ...  152
6773   51  82           10  376   474   605   967  1234  1287  1242  ...   55
7137   83  86            0  365   474   728  1256  1608  1670  1623  ...  115

                              endmembers
     2460 2470 2480 2490 2500      FIPPI PPI ATGP NFINDR
25     69   47   28    9   12          0   0    1      1
83      4    5    0   -2   -9          1   0    1      0
509    14   11   10    5    2          1   0    0      0
1082    8   13    2    1    1          0   0    0      1
1091  215  252  278  307  325          1   1    1      1
1174   10    7    6    1    2          1   0    1      1
2372  116   78   42   18   25          0   1    0      0
2373  116   80   40   13   27          0   1    0      0
2374  114   73   43   13   23          0   1    0      0
4859   61   43   22    7    9          0   0    0      1
5310  222  158   93   33   50          1   1    1      1
6773   73   55   29   13   13          0   0    1      0
7137  165  120   63   19   41          0   1    0      0

[13 rows x 211 columns]